/**
 * incoming socket.io events from the server
 */
export const SOCKET_IO = {
  ON_CURRENT_USER_JOIN_ROOM: 'ON_CURRENT_USER_JOIN_ROOM',
  ON_USERS_IN_ROOM: 'ON_USERS_IN_ROOM',
  ON_MESSAGE: 'ON_MESSAGE',
  ON_START_GAME: 'ON_START_GAME',
  ON_UPDATE_PLAYER_HAND: 'ON_UPDATE_PLAYER_HAND',
  ON_UPDATE_GAME_STATE: 'ON_UPDATE_GAME_STATE',
};

/**
 * client-side redux actions - which become socket.io events
 */
export const ACTION = {
  ...SOCKET_IO,
  CONNECT: 'API_CONNECT',
  DISCONNECT: 'API_DISCONNECT',
  SIGN_UP: 'SIGN_UP',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  JOIN_ROOM: 'JOIN_ROOM',
  MESSAGE: 'MESSAGE',
  READY_TO_START: 'READY_TO_START',
  DRAW_FROM_DECK: 'DRAW_FROM_DECK',
  DRAW_FROM_DISCARD: 'DRAW_FROM_DISCARD',
  DISCARD_FROM_HAND: 'DISCARD_FROM_HAND',
  GO_OUT: 'GO_OUT',
  LAY_DOWN_CARDS: 'LAY_DOWN_CARDS'
};
